server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&serverTimezone=UTC
    username: root
    password: 45tokife
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          batch_size: 100
          order_inserts: true
          order_updates: true

logging:
  level:
    root: INFO
    org.springframework: INFO
    searchengine: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

jsoup:
  user-agent: "Mozilla/5.0 (compatible; MyBot/1.0)"
  referrer: "https://www.google.com"
  delay: 1000

indexing-settings:
  sites:
    - url: https://www.playback.ru/
      name: playback
    - url: https://www.nikoartgallery.com/
      name: gallery
    - url: https://www.svetlovka.ru/
      name: svetlovka

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    mappings:
      enabled: true
    health:
      show-details: always
    info:
      enabled: true
  spring:
    mvc:
      dispatch-trace-request: true